  name: Deploy CDK App

  on:
    push:
      branches:
        - main  # mainブランチへのプッシュをトリガー

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        # 1. リポジトリのチェックアウト
        - name: Checkout repository
          uses: actions/checkout@v3

        # 2. Node.js のセットアップ
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '22'  # 必要なNode.jsのバージョンを指定

        # 3. AWS CLIのセットアップ
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: 'ap-northeast-1'

        # 4. 依存ライブラリのインストール
        - name: Install dependencies
          working-directory: infra
          run: |
            npm install

        # 5. CDK デプロイ
        - name: Deploy CDK stack
          working-directory: infra
          run: |
            npx cdk deploy --require-approval never
